android.experimental.enableNewResourceShrinker.preciseShrinking=true
android.enableAppCompileTimeRClass=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.vfs.watch=true
android.r8.maxWorkers=4
android.native.buildOutput=verbose

# 自定义包名（覆盖默认 me.weishu.kernelsu）
KSU_PACKAGE_NAME=me.weishv.kernelsv
# 自定义应用名（可选）
KSU_NAME=KernelSV
